AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Layout/ExtraSpacing:
  Exclude:
    - 'db/schema.rb'

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'
  Exclude:
    - 'config/application.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*.rb'
